print("Pokemon Damage Calc")
Target = float(1)
WTH = float(1)
BDGE = float(1)
CTCAL = float(1)
RND = float(1)
STB = float(1.5)
TYPE = float(0.5)
BRN = float(1)
OTH = float(1)
MDF = float(Target*WTH*BDGE*CTCAL*RND*STB*TYPE*BRN*OTH)
LVL = int(90)
PWR = int(110)
ATK = int(205)
DEF = int(188)
DMG = float(((((2*LVL/5)+2)*PWR*(ATK/DEF)/50)+2)*MDF)
print("\nANS: "+str(DMG))